---
- name: Mount snapshot volume
  mount:
    name: /var/lib/elasticsearch/backup
    src: LABEL=snapshots
    fstype: ext4
    opts: defaults,noatime
    state: mounted
- name: Elasticsearch daily snapshot cronjob
  cron: name="Elasticsearch snapshot" cron_file=/etc/crontab minute="16" hour="3" backup="yes" user=nobody job="curl -XPUT http://127.0.0.1:9200/_snapshot/ipfs/snapshot_`date +'%y%m%d-%H%M'` | jq -e '.accepted' > /dev/null"
