types:
  - audio:
    - audio/*
    - application/ogg
  - video:
    - video/*
    - application/mp4
  - documents:
    - text/html
    - text/plain
    - application/pdf
    - application/postscript
    - application/rtf
    - application/epub+zip
    - application/x-mobipocket-ebook
    - "*excel"
    - "*word"
    - "*powerpoint"
    - "*document*"
  - images:
    - image/*
analyzed_fields:
  - title
  - description
  - artist
  - author
