---
- name: download go-ipfs binary
  get_url: url={{ binary_url }} checksum=sha256:{{ binary_hash }} dest=/tmp/go-ipfs.tar.gz
  register: ipfs
- block:
    - name: extract go-ipfs archive
      unarchive: copy=no src=/tmp/go-ipfs.tar.gz dest=/tmp/
    - name: installing go-ipfs
      shell: /tmp/go-ipfs/install.sh
      become: true
    - name: remove temporary files
      file: state=absent path=/tmp/go-ipfs
  when: ipfs.changed
- block:
    - group: name=ipfs system=true state=present
    - user: name=ipfs comment="IPFS daemon" group=ipfs system=true state=present home={{ ipfs_path }}
    - file: path={{ ipfs_path }} owner=ipfs group=ipfs mode=750 state=directory
  become: true
